//We are only getting the cryptos code form the websocket, so this function
// maps the code to the actual crypto name to display on the CoinTile.
String getCryptoFullName(String symbol) {
  Map<String, String> cryptoNames = {
    'AMPYCINR': 'Amp',
    'BTCINR': 'Bitcoin',
    'ETHINR': 'Ethereum',
    'NEOINR': 'NEO',
    'LTCINR': 'Litecoin',
    'QTUMINR': 'Qtum',
    'ADAINR': 'Cardano',
    'XRPINR': 'Ripple',
    'EOSINR': 'EOS',
    'IOTAINR': 'IOTA',
    'XLMINR': 'Stellar',
    'TRXINR': 'Tron',
    'ETCINR': 'Ethereum Classic',
    'ICXINR': 'ICON',
    'VETINR': 'VeChain',
    'LINKINR': 'Chainlink',
    'WAVESINR': 'Waves',
    'HOTINR': 'Holo',
    'FETINR': 'Fetch.ai',
    'BATINR': 'Basic Attention Token',
    'XMRINR': 'Monero',
    'ZECINR': 'Zcash',
    'IOSTINR': 'IOST',
    'DASHINR': 'Dash',
    'OMGINR': 'OMG Network',
    'ENJINR': 'Enjin Coin',
    'MATICINR': 'Polygon',
    'ATOMINR': 'Cosmos',
    'FTMINR': 'Fantom',
    'ALGOINR': 'Algorand',
    'DOGEINR': 'Dogecoin',
    'DUSKINR': 'Dusk Network',
    'COSINR': 'Contentos',
    'DENTINR': 'Dent',
    'KEYINR': 'SelfKey',
    'CHZINR': 'Chiliz',
    'BANDINR': 'Band Protocol',
    'XTZINR': 'Tezos',
    'RVNINR': 'Ravencoin',
    'HBARINR': 'Hedera',
    'KAVAINR': 'Kava',
    'ARPAINR': 'ARPA Chain',
    'CTXCINR': 'Cortex',
    'BCHINR': 'Bitcoin Cash',
    'BNTINR': 'Bancor',
    'SOLINR': 'Solana',
    'CHRINR': 'Chromia',
    'COMPINR': 'Compound',
    'SCINR': 'Siacoin',
    'ZENINR': 'Horizen',
    'MKRINR': 'Maker',
    'MANAINR': 'Decentraland',
    'YFIINR': 'Yearn Finance',
    'BLZINR': 'Bluzelle',
    'SRMINR': 'Serum',
    'CRVINR': 'Curve DAO Token',
    'SANDINR': 'The Sandbox',
    'OCEANINR': 'Ocean Protocol',
    'DOTINR': 'Polkadot',
    'RSRINR': 'Reserve Rights',
    'TRINRT': 'Trias',
    'SUSHIINR': 'SushiSwap',
    'KSMINR': 'Kusama',
    'EGLDINR': 'Elrond',
    'RUNEINR': 'Thorchain',
    'UMAINR': 'UMA',
    'BELINR': 'Bella Protocol',
    'UNIINR': 'Uniswap',
    'AVAXINR': 'Avalanche',
    'AAVEINR': 'Aave',
    'NEARINR': 'Near Protocol',
    'FILINR': 'Filecoin',
    'INJINR': 'Injective Protocol',
    'AXSINR': 'Axie Infinity',
    'UNFIINR': 'Unifi Protocol DAO',
    'ROSEINR': 'Oasis Network',
    'SKLINR': 'SKALE Network',
    'GRTINR': 'The Graph',
    '1INCHINR': '1inch',
    'REEFINR': 'Reef Finance',
    'CELOINR': 'Celo',
    'FIROINR': 'Firo',
    'LITINR': 'Litentry',
    'CAKEINR': 'PancakeSwap',
    'ALICEINR': 'MyNeighborAlice',
    'TLMINR': 'Alien Worlds',
    'BAKEINR': 'BakeryToken',
    'SHIINRT': 'SHIBA INU',
    'MASKINR': 'Mask Network',
    'LPTINR': 'Livepeer',
    'ATAINR': 'Automata',
    'GTCINR': 'Gitcoin',
    'KLAYINR': 'Klaytn',
    'C98INR': 'Coin98',
    'MBOXINR': 'MOBOX',
    'REQINR': 'Request',
    'DYDXINR': 'dYdX',
    'IDEXINR': 'IDEX',
    'GALAINR': 'Gala',
    'SYSINR': 'Syscoin',
    'RAREINR': 'SuperRare',
    'DARINR': 'Mines of Dalarnia',
    'BNXINR': 'BinaryX',
    'ENSINR': 'Ethereum Name Service',
    'JASMYINR': 'JasmyCoin',
    'AMPINR': 'Amp',
    'FXSINR': 'Frax Share',
    'VOXELINR': 'Voxies',
    'PEOPLEINR': 'ConstitutionDAO',
    'SPELLINR': 'Spell Token',
    'JOEINR': 'Trader Joe',
    'IMXINR': 'Immutable X',
    'API3INR': 'API3',
    'BTTCINR': 'BitTorrent',
    'GMTINR': 'STEPN',
    'APEINR': 'ApeCoin',
    'GALINR': 'Project Galaxy',
    'LDOINR': 'Lido DAO',
    'OPINR': 'Optimism',
    'GMXINR': 'GMX',
    'APTINR': 'Aptos',
    'HFTINR': 'Hashflow',
    'MAGICINR': 'Magic',
    'AGIXINR': 'SingularityNET',
    'GASINR': 'Gas',
    'GLMINR': 'Golem',
    'ARKINR': 'Ark'
  };

  return cryptoNames[symbol] ?? 'Unknown Cryptocurrency';
}

//The websocket server is not giving any logos for the Coins,
// So generated this map to get logo based on the coins Code.
Map<String, String> cryptoLogos = {
  'AMPYCINR': 'https://cryptologos.cc/logos/amp-amp-logo.png',
  'BTCINR': 'https://cryptologos.cc/logos/bitcoin-btc-logo.png',
  'ETHINR': 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
  'NEOINR': 'https://cryptologos.cc/logos/neo-neo-logo.png',
  'LTCINR': 'https://cryptologos.cc/logos/litecoin-ltc-logo.png',
  'QTUMINR': 'https://cryptologos.cc/logos/qtum-qtum-logo.png',
  'ADAINR': 'https://cryptologos.cc/logos/cardano-ada-logo.png',
  'XRPINR': 'https://cryptologos.cc/logos/xrp-xrp-logo.png',
  'EOSINR': 'https://cryptologos.cc/logos/eos-eos-logo.png',
  'IOTAINR': 'https://cryptologos.cc/logos/iota-miota-logo.png',
  'XLMINR': 'https://cryptologos.cc/logos/stellar-xlm-logo.png',
  'TRXINR': 'https://cryptologos.cc/logos/tron-trx-logo.png',
  'ETCINR': 'https://cryptologos.cc/logos/ethereum-classic-etc-logo.png',
  'ICXINR': 'https://cryptologos.cc/logos/icon-icx-logo.png',
  'VETINR': 'https://cryptologos.cc/logos/vechain-vet-logo.png',
  'LINKINR': 'https://cryptologos.cc/logos/chainlink-link-logo.png',
  'WAVESINR': 'https://cryptologos.cc/logos/waves-waves-logo.png',
  'HOTINR': 'https://cryptologos.cc/logos/holo-hot-logo.png',
  'FETINR': 'https://cryptologos.cc/logos/fetch-ai-fet-logo.png',
  'BATINR': 'https://cryptologos.cc/logos/basic-attention-token-bat-logo.png',
  'XMRINR': 'https://cryptologos.cc/logos/monero-xmr-logo.png',
  'ZECINR': 'https://cryptologos.cc/logos/zcash-zec-logo.png',
  'IOSTINR': 'https://cryptologos.cc/logos/iost-iost-logo.png',
  'DASHINR': 'https://cryptologos.cc/logos/dash-dash-logo.png',
  'OMGINR': 'https://cryptologos.cc/logos/omg-network-omg-logo.png',
  'ENJINR': 'https://cryptologos.cc/logos/enjin-coin-enj-logo.png',
  'MATICINR': 'https://cryptologos.cc/logos/polygon-matic-logo.png',
  'ATOMINR': 'https://cryptologos.cc/logos/cosmos-atom-logo.png',
  'FTMINR': 'https://cryptologos.cc/logos/fantom-ftm-logo.png',
  'ALGOINR': 'https://cryptologos.cc/logos/algorand-algo-logo.png',
  'DOGEINR': 'https://cryptologos.cc/logos/dogecoin-doge-logo.png',
  'DUSKINR': 'https://cryptologos.cc/logos/dusk-network-dusk-logo.png',
  'COSINR': 'https://cryptologos.cc/logos/contentos-cos-logo.png',
  'DENTINR': 'https://cryptologos.cc/logos/dent-dent-logo.png',
  'KEYINR': 'https://cryptologos.cc/logos/selfkey-key-logo.png',
  'CHZINR': 'https://cryptologos.cc/logos/chiliz-chz-logo.png',
  'BANDINR': 'https://cryptologos.cc/logos/band-protocol-band-logo.png',
  'XTZINR': 'https://cryptologos.cc/logos/tezos-xtz-logo.png',
  'RVNINR': 'https://cryptologos.cc/logos/ravencoin-rvn-logo.png',
  'HBARINR': 'https://cryptologos.cc/logos/hedera-hbar-logo.png',
  'KAVAINR': 'https://cryptologos.cc/logos/kava-kava-logo.png',
  'ARPAINR': 'https://cryptologos.cc/logos/arpa-chain-arpa-logo.png',
  'CTXCINR': 'https://cryptologos.cc/logos/cortex-ctxc-logo.png',
  'BCHINR': 'https://cryptologos.cc/logos/bitcoin-cash-bch-logo.png',
  'BNTINR': 'https://cryptologos.cc/logos/bancor-bnt-logo.png',
  'SOLINR': 'https://cryptologos.cc/logos/solana-sol-logo.png',
  'CHRINR': 'https://cryptologos.cc/logos/chromia-chr-logo.png',
  'COMPINR': 'https://cryptologos.cc/logos/compound-comp-logo.png',
  'SCINR': 'https://cryptologos.cc/logos/siacoin-sc-logo.png',
  'ZENINR': 'https://cryptologos.cc/logos/horizen-zen-logo.png',
  'MKRINR': 'https://cryptologos.cc/logos/maker-mkr-logo.png',
  'MANAINR': 'https://cryptologos.cc/logos/decentraland-mana-logo.png',
  'YFIINR': 'https://cryptologos.cc/logos/yearn-finance-yfi-logo.png',
  'BLZINR': 'https://cryptologos.cc/logos/bluzelle-blz-logo.png',
  'SRMINR': 'https://cryptologos.cc/logos/serum-srm-logo.png',
  'CRVINR': 'https://cryptologos.cc/logos/curve-dao-token-crv-logo.png',
  'SANDINR': 'https://cryptologos.cc/logos/the-sandbox-sand-logo.png',
  'OCEANINR': 'https://cryptologos.cc/logos/ocean-protocol-ocean-logo.png',
  'DOTINR': 'https://cryptologos.cc/logos/polkadot-dot-logo.png',
  'RSRINR': 'https://cryptologos.cc/logos/reserve-rights-rsr-logo.png',
  'TRINRT': 'https://cryptologos.cc/logos/trias-tri-logo.png',
  'SUSHIINR': 'https://cryptologos.cc/logos/sushiswap-sushi-logo.png',
  'KSMINR': 'https://cryptologos.cc/logos/kusama-ksm-logo.png',
  'EGLDINR': 'https://cryptologos.cc/logos/multiversx-egld-logo.png',
  'RUNEINR': 'https://cryptologos.cc/logos/thorchain-rune-logo.png',
  'UMAINR': 'https://cryptologos.cc/logos/uma-uma-logo.png',
  'BELINR': 'https://cryptologos.cc/logos/bella-protocol-bel-logo.png',
  'UNIINR': 'https://cryptologos.cc/logos/uniswap-uni-logo.png',
  'AVAXINR': 'https://cryptologos.cc/logos/avalanche-avax-logo.png',
  'AAVEINR': 'https://cryptologos.cc/logos/aave-aave-logo.png',
  'NEARINR': 'https://cryptologos.cc/logos/near-protocol-near-logo.png',
  'FILINR': 'https://cryptologos.cc/logos/filecoin-fil-logo.png',
  'INJINR': 'https://cryptologos.cc/logos/injective-inj-logo.png',
  'AXSINR': 'https://cryptologos.cc/logos/axie-infinity-axs-logo.png',
  'UNFIINR': 'https://cryptologos.cc/logos/unifi-protocol-dao-unfi-logo.png',
  'ROSEINR': 'https://cryptologos.cc/logos/oasis-network-rose-logo.png',
  'SKLINR': 'https://cryptologos.cc/logos/skale-network-skl-logo.png',
  'GRTINR': 'https://cryptologos.cc/logos/the-graph-grt-logo.png',
  '1INCHINR': 'https://cryptologos.cc/logos/1inch-1inch-logo.png',
  'REEFINR': 'https://cryptologos.cc/logos/reef-finance-reef-logo.png',
  'CELOINR': 'https://cryptologos.cc/logos/celo-celo-logo.png',
  'FIROINR': 'https://cryptologos.cc/logos/firo-firo-logo.png',
  'LITINR': 'https://cryptologos.cc/logos/litentry-lit-logo.png',
  'CAKEINR': 'https://cryptologos.cc/logos/pancakeswap-cake-logo.png',
  'ALICEINR': 'https://cryptologos.cc/logos/myneighboralice-alice-logo.png',
  'TLMINR': 'https://cryptologos.cc/logos/alien-worlds-tlm-logo.png',
  'BAKEINR': 'https://cryptologos.cc/logos/bake-protocol-bake-logo.png',
  'SHIINRT': 'https://cryptologos.cc/logos/shiba-inu-shi-logo.png',
  'MASKINR': 'https://cryptologos.cc/logos/mask-network-mask-logo.png',
  'LPTINR': 'https://cryptologos.cc/logos/livepeer-lpt-logo.png',
  'ATAINR': 'https://cryptologos.cc/logos/automata-ata-logo.png',
  'GTCINR': 'https://cryptologos.cc/logos/gitcoin-gtc-logo.png',
  'KLAYINR': 'https://cryptologos.cc/logos/klaytn-klay-logo.png',
  'C98INR': 'https://cryptologos.cc/logos/cake-c98-logo.png',
  'MBOXINR': 'https://cryptologos.cc/logos/mobox-mbox-logo.png',
  'REQINR': 'https://cryptologos.cc/logos/request-request-logo.png',
  'DYDXINR': 'https://cryptologos.cc/logos/dydx-dydx-logo.png',
  'IDEXINR': 'https://cryptologos.cc/logos/idex-idex-logo.png',
  'GALAINR': 'https://cryptologos.cc/logos/gala-gala-logo.png',
  'SYSINR': 'https://cryptologos.cc/logos/syscoin-sys-logo.png',
  'RAREINR': 'https://cryptologos.cc/logos/rare-rar-logo.png',
  'DARINR': 'https://cryptologos.cc/logos/darwinia-network-dar-logo.png',
  'BNXINR': 'https://cryptologos.cc/logos/bnx-coin-bnx-logo.png',
  'ENSINR': 'https://cryptologos.cc/logos/ens-dao-ens-logo.png',
  'JASMYINR': 'https://cryptologos.cc/logos/jasmycoin-jasmy-logo.png',
  'AMPINR': 'https://cryptologos.cc/logos/amp-amp-logo.png',
  'FXSINR': 'https://cryptologos.cc/logos/frax-share-fxs-logo.png',
  'VOXELINR': 'https://cryptologos.cc/logos/vox-voxel-logo.png',
  'PEOPLEINR': 'https://cryptologos.cc/logos/constitutiondao-people-logo.png',
  'SPELLINR': 'https://cryptologos.cc/logos/spell-token-spell-logo.png',
  'JOEINR': 'https://cryptologos.cc/logos/trader-joe-joe-logo.png',
  'IMXINR': 'https://cryptologos.cc/logos/immutable-x-imx-logo.png',
  'API3INR': 'https://cryptologos.cc/logos/api3-api3-logo.png',
  'BTTCINR': 'https://cryptologos.cc/logos/bittorrent-bttc-logo.png',
  'GMTINR': 'https://cryptologos.cc/logos/steppn-gmt-logo.png',
  'APEINR': 'https://cryptologos.cc/logos/ape-ape-logo.png',
  'GALINR': 'https://cryptologos.cc/logos/project-galaxy-gal-logo.png',
  'LDOINR': 'https://cryptologos.cc/logos/lido-dao-ldo-logo.png',
  'OPINR': 'https://cryptologos.cc/logos/optimism-op-logo.png',
  'GMXINR': 'https://cryptologos.cc/logos/gmx-gmx-logo.png',
  'APTINR': 'https://cryptologos.cc/logos/aptos-apt-logo.png',
  'HFTINR': 'https://cryptologos.cc/logos/hashflow-hft-logo.png',
  'MAGICINR': 'https://cryptologos.cc/logos/magic-magic-logo.png',
  'AGIXINR': 'https://cryptologos.cc/logos/singularitynet-agix-logo.png',
  'GASINR': 'https://cryptologos.cc/logos/gas-gas-logo.png',
  'GLMINR': 'https://cryptologos.cc/logos/golem-glm-logo.png',
  'ARKINR': 'https://cryptologos.cc/logos/ark-ark-logo.png'
};

//dummy values of PercentChange
// to be used only till real data is unavailable
List<String> dummyPercentChange = [
  "+00.00",
  "+14.05%",
  "+12.32%",
  "+9.42%",
  "+7.43%",
  "+6.01%",
  "+1.09%"
];

//dummy values of Price
// to be used only till real data is unavailable
List<String> dummyPrice = [
  "000000",
  "4987450",
  "217300",
  "844.83",
  "5246.90",
  "205.10",
  "29.55"
];